name: Push_release_w/_tag

on:
  push:
    tags:
      - 'v*'
                        
jobs:
  Make_GitHub_Release:
    name: create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
                        
    - name: release
      id: create_release
      uses: marvinpinto/action-automatic-releases@latest
      with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          tag_name: ${{ github.ref }}
          release_name: release ${{ github.ref }}
          body: |
            Upload archive and binary files for uploading
          draft: false
          prerelease: false

  Archives:
    needs: Make_GitHub_Release
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3

    - name: prepare environment
      run: |
        cmake --version
    - name: build achive files
      run : |
        mkdir cmake && cd cmake
        cmake -DGENERATOR=ARC ..
        make
        cpack -G TGZ
        cpack -G ZIP
    - name: TGZ
      id: TGZ
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.tar.gz
       asset_name: Solver-${{ github.ref_name }}.tar.gz
       asset_content_type: code/tgz
       
    - name: ZIP
      id: ZIP
      uses: actions/upload-release-asset@v1
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
       upload_url: ${{ needs.Make_GitHub_Release.outputs.upload_url }}
       asset_path: ./cmake/solver-0.1.1-Linux.zip
       asset_name: Solver-${{ github.ref_name }}.zip
       asset_content_type: code/zip

 
